name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JDK_JAVA_DISTRIBUTION: 'temurin'
  JDK_JAVA_VERSION: '17'

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: [ ubuntu-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_JAVA_DISTRIBUTION }}
          java-version: ${{ env.JDK_JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Static Analysis Tools
        run: ./gradlew lint --continue

  test:
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_JAVA_DISTRIBUTION }}
          java-version: ${{ env.JDK_JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Unit Tests
        run: ./gradlew test

  assemble:
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_JAVA_DISTRIBUTION }}
          java-version: ${{ env.JDK_JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug APK
        run: ./gradlew assembleDebug