name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: [ ubuntu-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Run Static Analysis Tools
        run: ./gradlew lint --continue

  test:
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Run Unit Tests
        run: ./gradlew test

  assemble:
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Build Debug APK
        run: ./gradlew assembleDebug